server:
  port: 9898
  servlet:
    context-path: /covid
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/covid
    data-username: root
    data-password: root

  batch:
    job:
      enabled: false